### PR TITLE
cleans up transactions

### PR DESCRIPTION
**Pull request by andricDu**
No need for transactions on getters

### CODE REVIEW

**Comment by blabadi** [comment]
I don't know if removing the transactions annotations from repos actually has any effect because the repository adds it by default .. hibernate does need a transaction on every connection even if it's an sql read

**Comment by andricDu** [comment]
> I don't know if removing the transactions annotations from repos actually has any effect because the repository adds it by default .. hibernate does need a transaction on every connection even if it's an sql read

You are correct. I was cleaning up transactions where they are needed due to all being called inside a transnational context.

**Comment by blabadi** [comment]
So the root cause still unknown i believe

**Comment by andricDu** [comment]
@blabadi some research indicated that calling all non-mutating get operations inside transactional contexts could lead to some hard to diagnose bugs. Give than a page load right now on the program dashboard in dev triggers probably close to 100 get operations, having those all being managed by a runtime transaction proxy could be causing some of the stuff we are seeing.

**Comment by andricDu** [comment]
But yes, I'm not 100% convinced this is the real cause.

**Pull request merged**
